services:
  app:
    build: .
    container_name: simply-shopping-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: [ 'sleep', 'infinity' ]
    depends_on:
      - database
    networks:
      - simply-shopping-network

  database:
    image: public.ecr.aws/docker/library/postgres:15
    container_name: simply-shopping-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: simply_shopping
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - simply-shopping-network

  pgadmin:
    image: public.ecr.aws/big-wave-tech/pgadmin4:7
    container_name: simply-shopping-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - database
    networks:
      - simply-shopping-network

volumes:
  database-data:


networks:
  simply-shopping-network:
    external: true