this updated compose:

services:
  app:
    build: .
    container_name: simply-shopping-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: [ 'sleep', 'infinity' ]
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123
      - DB_NAME=simply_shopping
    depends_on:
      - database
    networks:
      - simply-shopping-network

  database:
    image: public.ecr.aws/docker/library/postgres:15
    container_name: simply-shopping-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: simply_shopping
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - simply-shopping-network

volumes:
  database-data:


networks:
  simply-shopping-network:
    external: true